### ISSUE TITLE
Something confusion about neural_networks.py

### ISSUE THREAD

**Issue by dayanbatuofu** [Tenavi/HJB_NN#2]
Hi Tenavi,

    Thanks for sharing your code. This code is very helpful for my current research. But I have one question about your code in line 144, neural_networks.py. I am not sure why you use 'V = tf.concat([V, 2.0*t/self.t1 - 1.0], axis=0)'. If you use this syntax here, let's consider satellite example, the layer is [6, 64, 64, 64, 1]. It means that the dimension for the weight is 64x6, 64x64, 64x64, 1x64. Before using 'V = tf.concat([V, 2.0*t/self.t1 - 1.0], axis=0)', the dimension of V is 6xN (N means any numbers). After using 'V = tf.concat([V, 2.0*t/self.t1 - 1.0], axis=0)', the dimension of V is 7xN. So I think there is a bug for the matrix multiply. Hope you could give me some suggestions about your ideas.

Thanks,

Lei Zhang

**Comment by Tenavi** [comment]
Hi Lei,

Thanks for your interest! What this line does is concatenate the input for X, `2.0*(X - self.lb)/(self.ub - self.lb) - 1.0`, and the input for t, `2.0*t/self.t1 - 1.0`. This is because the value function is, in general, a function of (t,X). In contrast, for modeling just the initial time value function the extra line for concatenating with t is not needed (see line 524).

I hope this answers your question! Best,
Tenavi
